// This file was generated by img2gb, DO NOT EDIT

#ifndef _CUBE_BG_R_TILEMAP_H
#define _CUBE_BG_R_TILEMAP_H

extern const UINT8 CUBE_BG_TILEMAP[];
#define CUBE_BG_TILEMAP_WIDTH 20
#define CUBE_BG_TILEMAP_HEIGHT 18


#endif
