// This file was generated by img2gb, DO NOT EDIT

#ifndef _WANADEV_LOGO_L_TILESET_H
#define _WANADEV_LOGO_L_TILESET_H

extern const UINT8 WANADEV_LOGO_TILESET[];
#define WANADEV_LOGO_TILESET_TILE_COUNT 102


#endif
